IC_MODULES = {
    "bi": "inputs.baroclinic_instability_periodic",
    "tv": "inputs.travelling_vortex_2D",
    "tv_2d": "inputs.travelling_vortex_2D",
    "tv_neg": "inputs.travelling_vortex_2D_neg",
    "tv_3d": "inputs.travelling_vortex_3D",
    "tv_corr": "inputs.travelling_vortex_3D_Coriolis",
    "aw": "inputs.acoustic_wave_high",
    "igw": "inputs.internal_long_wave",
    "igw_3d": "inputs.internal_long_wave_3D",
    "lbw": "inputs.lamb_waves",
    "skl": "inputs.sk_lamb_wave",
    "mark": "inputs.mark",
    "lw_p": "inputs.lamb_wave_perturb",
    "igw_bb": "inputs.igw_baldauf_brdar",
    "rb": "inputs.rising_bubble",
    "rbc": "inputs.rising_bubble_cold",
    "swe_bal_vortex": "inputs.swe_bal_vortex",
    "swe": "inputs.shallow_water_3D",
    "swe_icshear": "inputs.shallow_water_3D_icshear",
    "swe_dvortex": "inputs.shallow_water_3D_dvortex",
    "test_travelling_vortex": "pybella.tests.test_travelling_vortex",  
    "test_internal_long_wave": "pybella.tests.test_internal_long_wave",
    "test_lamb_wave": "pybella.tests.test_lamb_wave",
    "test_blending_warm_bubble": "pybella.tests.test_blending_warm_bubble",
    "test_unstable_lamb": "pybella.tests.test_unstable_lamb",
}