name: deploy

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  get-runner:
    runs-on: ubuntu-latest
    outputs:
     RUNNER: ${{ runner.name }}
    steps:
      - run: echo "selected runner = ${{ runner.name }}"
  prepare:
    needs: get-runner
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    outputs:
     RUNNER: ${{ runner.name }}
    steps:
      - uses: actions/checkout@v3
      - uses: ConorMacBride/install-package@v1
        with:
          apt: graphviz
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10.5' 
      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
          pip install .
  docs:
    needs: prepare
    runs-on: ${{needs.prepare.outputs.RUNNER}}
    steps:
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
  dycore:
    needs: prepare
    runs-on: ${{needs.prepare.outputs.RUNNER}}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          pytest ./run_scripts/test_dycore.py --no-header -v
    