name: tests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  dycore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10.5' 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .
      - name: Run tests
        run: |
          pytest ./run_scripts/test_dycore.py --no-header -v